// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test/command.proto

// Protobuf Java Version: 4.26.1
package cn.learn.netty.im.packet.command;

public interface LoginResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cn.learn.netty.LoginResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   * @return The success.
   */
  boolean getSuccess();

  /**
   * <code>string reason = 2;</code>
   * @return The reason.
   */
  String getReason();
  /**
   * <code>string reason = 2;</code>
   * @return The bytes for reason.
   */
  com.google.protobuf.ByteString
      getReasonBytes();
}
