// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test/command.proto

// Protobuf Java Version: 4.26.1
package cn.learn.netty.im.packet.command;

public interface MessageRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cn.learn.netty.MessageRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
