spring:
  datasource:
    username: root
    password: 5EYcHss4
    url: jdbc:mysql://121.36.136.81:3306/games?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    #指定连接池类型  不配置的话Spring默认为HikariDataSource
    type: com.zaxxer.hikari.HikariDataSource
#mybatis
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true